#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<html>"
echo "<meta http-equiv="refresh" content="4\;url=check.cgi" />"
echo "<head><title>WAN Gateways"
echo "</title>"
echo "<style>"
echo "</style>"
echo "</head><body>"
wangw=$(sudo cat /var/log/pfsense_gateway_alarm.log)
echo "$(if [[ ${wangw} == *WANGW* ]]; then sudo sed -i 's/: #.*/: #FF0000;"/g' /usr/lib/cgi-bin/wangw.cgi; fi)"
echo "$(if [[ ${wangw} == *WANALT* ]]; then sudo sed -i 's/: #.*/: #FF0000;"/g' /usr/lib/cgi-bin/wanalt_dhcp.cgi; fi)"
echo "$(if [[ ${wangw} == *WANTER* ]]; then sudo sed -i 's/: #.*/: #FF0000;"/g' /usr/lib/cgi-bin/wantertiary_dhcp.cgi; fi)"
echo "$(if [[ ${wangw} == *MGMT* ]]; then sudo sed -i 's/: #.*/: #FF0000;"/g' /usr/lib/cgi-bin/mgmt.cgi; fi)"
echo "$(if [[ ${wangw} == *NETHER* ]]; then sudo sed -i 's/: #.*/: #FF0000;"/g' /usr/lib/cgi-bin/netherlands.cgi; fi)"
echo "$(if [[ ${wangw} == *LONDON* ]]; then sudo sed -i 's/: #.*/: #FF0000;"/g' /usr/lib/cgi-bin/london.cgi; fi)"
echo "<br>"
echo "<br>"
echo "</body></html>"
