#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<html>"
echo "<meta http-equiv="refresh" content="5\;url=check.cgi" />"
echo "<head><title>WAN Gateways"
echo "</title>"
echo "<style>"
echo "</style>"
echo "</head><body>"
wangw=$(sudo cat /var/log/pfsense_gateway_alarm.log)
echo "$(if [[ ${wangw} == *WANGW* ]] && [[ ! -e /home/www-data/wanpri.txt ]]; then echo "triggered" > /home/www-data/wanpri.txt; sudo sed -i 's/: #.*/: #FF0000;"/g' /usr/lib/cgi-bin/wangw.cgi && echo "$(date "+%Y-%m-%e %T") --- WANGW 75Mb went down<br>" >> /home/www-data/temp.log; cat /home/www-data/pfsense_gw.log >> /home/www-data/temp.log; mv /home/www-data/temp.log /home/www-data/pfsense_gw.log; fi)"
echo "$(if [[ ${wangw} == *WANALT* ]] && [[ ! -e /home/www-data/wanalt.txt ]]; then echo "triggered" > /home/www-data/wanalt.txt; sudo sed -i 's/: #.*/: #FF0000;"/g' /usr/lib/cgi-bin/wanalt_dhcp.cgi && echo "$(date "+%Y-%m-%e %T") --- WANALT_DHCP 20Mb went down<br>" >> /home/www-data/temp.log; cat /home/www-data/pfsense_gw.log >> /home/www-data/temp.log; mv /home/www-data/temp.log /home/www-data/pfsense_gw.log; fi)"
echo "$(if [[ ${wangw} == *WANTER* ]] && [[ ! -e /home/www-data/wanter.txt ]]; then echo "triggered" > /home/www-data/wanter.txt; sudo sed -i 's/: #.*/: #FF0000;"/g' /usr/lib/cgi-bin/wantertiary_dhcp.cgi && echo "$(date "+%Y-%m-%e %T") --- WANTERTIARY_DHCP 20Mb went down<br>" >> /home/www-data/temp.log; cat /home/www-data/pfsense_gw.log >> /home/www-data/temp.log; mv /home/www-data/temp.log /home/www-data/pfsense_gw.log; fi)"
echo "$(if [[ ${wangw} == *MGMT* ]] && [[ ! -e /home/www-data/vpnmgmt.txt ]]; then echo "triggered" > /home/www-data/vpnmgmt.txt; sudo sed -i 's/: #.*/: #FF0000;"/g' /usr/lib/cgi-bin/mgmt.cgi && echo "$(date "+%Y-%m-%e %T") --- MGMT VPN went down<br>" >> /home/www-data/temp.log; cat /home/www-data/pfsense_gw.log >> /home/www-data/temp.log; mv /home/www-data/temp.log /home/www-data/pfsense_gw.log; fi)"
echo "$(if [[ ${wangw} == *NETHER* ]] && [[ ! -e /home/www-data/vpnnet.txt ]]; then echo "triggered" > /home/www-data/vpnnet.txt; sudo sed -i 's/: #.*/: #FF0000;"/g' /usr/lib/cgi-bin/netherlands.cgi && echo "$(date "+%Y-%m-%e %T") --- Netherlands VPN went down<br>" >> /home/www-data/temp.log; cat /home/www-data/pfsense_gw.log >> /home/www-data/temp.log; mv /home/www-data/temp.log /home/www-data/pfsense_gw.log; fi)"
echo "$(if [[ ${wangw} == *LONDON* ]] && [[ ! -e /home/www-data/vpnlon.txt ]]; then echo "triggered" > /home/www-data/vpnlon.txt; sudo sed -i 's/: #.*/: #FF0000;"/g' /usr/lib/cgi-bin/london.cgi && echo "$(date "+%Y-%m-%e %T") --- London VPN went down<br>" >> /home/www-data/temp.log; cat /home/www-data/pfsense_gw.log >> /home/www-data/temp.log; mv /home/www-data/temp.log /home/www-data/pfsense_gw.log; fi)"
echo "<br>"
echo "<br>"
echo "</body></html>"
                      
