#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<html>"
echo "<head><title>Logs"
echo "</title>"
echo "<style>"
echo "</style>"
echo "</head><body>"
echo "<br>"
echo "<p> </p><a href="../index.html">Main Menu</a>"
echo "<br>"
echo "<br>"
echo "$(cat /home/www-data/pfsense_gw.log)"
echo "<br>"
echo "<a href="./resetlog.cgi">Clear the Logs</a>"
echo "<br>"
echo "<a href="./archive.cgi">Check the archives</a>"
echo "</body></html>"
