#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<html>"
echo "<meta http-equiv="refresh" content="4\;url=../index.html" />"
echo "<head><title>Clear Logs"
echo "</title>"
echo "<style>"
echo "</style>"
echo "</head><body>"
echo "<br>"
echo " <a href="../index.html"> Return to Main Menu</a>"
echo "$(echo "$(date "+%Y-%m-%e %T") --- Log has been reset<br>" > /home/www-data/pfsense_gw.log)"
echo "<br>"
echo "</body></html>"
