#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<html>"
echo "<head><title>WAN Gateways"
echo "</title>"
echo "<style>"
echo "body {"
echo "  background-color: #FF0000;"
echo "}"
echo "</style>"
echo "</head><body>"
echo "<br>"
echo "<br>"
echo "</body></html>"
